package com.backend.core.enums;

public enum DeliveryEnum {
    SHIPPED,
    SHIPPING,
    NOT_SHIPPED,
    FAILED,
    SHIPPER_CANCEL,
    CUSTOMER_CANCEL,
    ACCEPTANCE_WAITING,
    PACKING,
    PAYMENT_WAITING,
    SHIPPER_WAITING,
    FIRST_ATTEMPT_FAILED,
    SECOND_ATTEMPT_FAILED,
    EXPRESS_DELIVERY,
    NORMAL_DELIVERY,
}