package com.backend.core.enums;

public enum FilterTypeEnum {
    PRODUCT,
    INVOICE,
    DELIVERY,
    CART_ITEMS,
    COMMENT,
    ACCOUNT,
    SHIP_HISTORY,
    MY_ORDERS,
    AVAILABLE_ORDERS,
    SHIPPER_WAITING_ORDERS,
    PACKING_ORDERS,
    SUCCESSFUL_ORDERS,
    FAILED_ORDERS,
    NOTIFICATION,
}
