package com.backend.core.enums;

public enum RenderTypeEnum {
    ALL_PRODUCTS,
    TOP_8_BEST_SELL_PRODUCTS,
    NEW_ARRIVAL_PRODUCTS,
    HOT_DISCOUNT_PRODUCTS,
    ALL_CART_ITEMS,
    CUSTOMER_ALL_CURRENT_INVOICES,
    CUSTOMER_PURCHASE_HISTORY,
    CUSTOMER_INVOICE_DETAILS,
    ADMIN_ALL_INVOICES,
    ALL_CATEGORIES,
}
