package com.backend.core.usecase.statics;

public enum RenderTypeEnum {
    ALL_PRODUCTS,
    TOP_8_BEST_SELL_PRODUCTS,
    NEW_ARRIVAL_PRODUCTS,
    HOT_DISCOUNT_PRODUCTS,
    TOTAL_PRODUCTS_QUANTITY,
    ALL_CART_ITEMS,
    CUSTOMER_INVOICE_DETAILS,
    ADMIN_ALL_INVOICES,
    ALL_CATEGORIES,
    CART_CHECKOUT,
    TOTAL_CART_ITEM_QUANTITY,
}
